hash-format = "sha256"

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "bedc5fd207a9959c72565f0131b65a8eec71dcdef3e83f6c4556f81e7292326a"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "084ec914d4aba5a139e1bfaeb67c6a6c7cf1ba22cfbf5ef96a46db49c830db96"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "1b222f2d73036e0d08be25c3c8c5a77a8454b1f399467ff212d09e936426734e"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "4ba45966a267b774f5d83442c3c43d740f55e11a910e117e50c046b4f77b5c66"
metafile = true

[[files]]
file = "mods/dynamic-view-fabric.pw.toml"
hash = "d9199e3e1d0c431a4fac4b7232718cf2b9fdc17d231471c351dd9090f16c551a"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "03e174cf691b52da20bd973b955fae6f3720d3d2120f9d6cc1de5fdf3180013c"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "71ef7cc16632c0039fe194183b5885968c6d740aaa67a58000653ae0cb40b882"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "97ffbc7d0e4087777c5e3732780f01958f99d44c4f09fd534bbb8f239d4980a1"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "ee293388d8578d1c91fb3b642c703eb4db43a9d736c2a94bd5bd365a9afa0baf"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "218f67d6bcaae849582618cd3e5eb1d4cac0fd6045115f64340620300e160c11"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "2008716fdfef554660ce44659a3a42acd673a5391af2d4bd94f40654f1f60a1d"
metafile = true
