name = "2023 Mk"
author = "Mics"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b9f5e362a3833a914b5440a8e4323453e26987406aab5a17b0ae7bf6bcd01b3"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"
