name = "2023 Mk"
author = "Mics"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07ac50a19f50b8a304f23f560778bd43d9f33fff40cebc68d11bc86ef690c99f"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"
